# Create the Drupal site you would like here
version: '2'
services:
  drupal:
    # Choose the URL and hostname for this Docker Container
    # NEEDS to end with '.docker.amazee.io' !
    # DO NOT remove the '&hostname'
    hostname: &hostname cachalot.docker.amazee.io

    environment:
      # If you use https://github.com/drupal-composer/drupal-project or something similar,
      # the Drupal root is not inside the repository root. Here you can define in which folder
      # the Drupal root lives
      WEBROOT: web

      # Disable alias loading via the web to reduce the time spent waiting for internet and also make tests more compareable
      AMAZEEIO_DISABLE_ALIASES: 'true'

      # APC Support is by enabled by default, but in some cases it can cause issues, change to 0 to disable:
      APC: 1


################################################
### Do not change anything below here, unless you know what know what you are doing.
      VIRTUAL_HOST: *hostname
    image: amazeeio/drupal:php70-basic
    volumes:
      - .:/var/www/drupal/public_html
      - ../composer-cache:/var/www/drupal/.composer/cache
    container_name: *hostname
    network_mode: bridge
